/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticaciondeproceso;

import automaticaciondeproceso.conections.Conection;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.regexp.joni.EncodingHelper;

/**
 *
 * @author wwwca
 */
public class frmasignaciondecatedra extends javax.swing.JFrame {
public int idcatedratico=-1;
public String nombre="";
public int catedra=-1;
public String materia="";
public int idmateria=-1;
 frmBuscarCatedratico catedratico;
    /**
     * Creates new form frmasignaciondecatedra
     */
    public frmasignaciondecatedra() {
        initComponents();
         this.setSize(new Dimension(740,300));
        catedratico=new frmBuscarCatedratico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaasignacion = new javax.swing.JTable();
        btnasignar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncatedra = new javax.swing.JButton();
        cbofacultad = new javax.swing.JComboBox<>();
        btnBuscarCatedratico = new javax.swing.JButton();
        lblcatedraticos = new javax.swing.JLabel();
        lblcatedras = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Curso");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Codigo Catedratico:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 30, 96, 14);

        jLabel2.setText("Codigo Catedra:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(417, 30, 79, 14);

        btnagregar.setText("agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar);
        btnagregar.setBounds(35, 67, 71, 23);

        tablaasignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codcatedratico", "Nombre Catedratico", "codcurso", "Nombre catedra", "facultad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaasignacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(35, 105, 686, 99);

        btnasignar.setText("Asignar");
        btnasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignarActionPerformed(evt);
            }
        });
        getContentPane().add(btnasignar);
        btnasignar.setBounds(652, 222, 69, 23);

        jLabel3.setText("Codigo Facultad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 71, 77, 14);

        btncatedra.setText("Curso");
        btncatedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatedraActionPerformed(evt);
            }
        });
        getContentPane().add(btncatedra);
        btncatedra.setBounds(506, 26, 140, 23);

        cbofacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en Sistemas", "Ciencias Juridicas y Sociales", "Administracion", "Psicologia Clinica", "Psicologia Industrial", "Ingles" }));
        cbofacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbofacultadActionPerformed(evt);
            }
        });
        getContentPane().add(cbofacultad);
        cbofacultad.setBounds(487, 68, 159, 20);

        btnBuscarCatedratico.setText("Buscar Catedratico");
        btnBuscarCatedratico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCatedraticoMouseClicked(evt);
            }
        });
        btnBuscarCatedratico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCatedraticoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarCatedratico);
        btnBuscarCatedratico.setBounds(143, 26, 145, 23);
        getContentPane().add(lblcatedraticos);
        lblcatedraticos.setBounds(298, 26, 113, 23);
        getContentPane().add(lblcatedras);
        lblcatedras.setBounds(656, 26, 65, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automaticaciondeproceso/fondo4.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 1, 740, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncatedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatedraActionPerformed
     frmBuscarCatedra catb=new frmBuscarCatedra();
        catb.setAlwaysOnTop(true);
       catb.setVisible(true);
       idmateria=catb.idcatedra;
       materia=catb.nombre;
        lblcatedras.setText("( Agregado )");
     //  txtcodcatedratico.setText(""+idmateria); 
    }//GEN-LAST:event_btncatedraActionPerformed

    private void btnBuscarCatedraticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCatedraticoActionPerformed
 
            catedratico.setAlwaysOnTop(true);
            catedratico.setVisible(true);    
            
            idcatedratico=data.idcatedratico;
            nombre=data.nombre;
            lblcatedraticos.setText("( Agregado )");
        //    txtcodcatedratico.setText(""+idcatedratico); 
            
    }//GEN-LAST:event_btnBuscarCatedraticoActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
    //    JOptionPane.showMessageDialog(rootPane, "id "+data.nombre);
        if(data.idcatedratico!=-1 && data.idmateria!=-1 && data.nombre!="" && data.nombre!=""){
               //limpiamos primero los de seleccion
                lblcatedraticos.setText("");
               lblcatedras.setText("");
               
                    DefaultTableModel modelo=(DefaultTableModel) tablaasignacion.getModel(); 
 
        //Sección 2
        Object [] fila=new Object[5]; 
 
        //Sección 3
        fila[0]=data.idcatedratico;
        fila[1]= data.nombre;
        fila[2]=data.idmateria; 
        fila[3]=data.materia; 
        fila[4]=(String) cbofacultad.getSelectedItem();
         //Sección 4
         modelo.addRow(fila); 
  
        //Sección 5
        tablaasignacion.setModel(modelo); 
            
            
            
            data.idcatedratico=-1;
               data.idmateria=-1;
               data.materia="";
               data.nombre="";
        }else if(data.idcatedratico==-1){
                JOptionPane.showMessageDialog(this, "No se ha seleccionado Docente");
        }else if(data.idmateria==-1){
                JOptionPane.showMessageDialog(this, "No se ha seleccionado materia");
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnBuscarCatedraticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCatedraticoMouseClicked
                 
    }//GEN-LAST:event_btnBuscarCatedraticoMouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
  idcatedratico=data.idcatedratico;
            nombre=data.nombre;
//            txtcodcatedratico.setText(""+idcatedratico);        
        
    }//GEN-LAST:event_formWindowStateChanged

    private void cbofacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbofacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbofacultadActionPerformed

    private void btnasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignarActionPerformed
     
       try {
           if(isvalid()){
            Conection conec=new Conection();
            
            while (tablaasignacion.getRowCount() > 0) {
                // tomamos la fecha actual para almacenar en la db
                java.util.Date date = new Date();
                java.sql.Date fechaActual = new java.sql.Date(date.getTime()); 
                int codfac=getcodigo(tablaasignacion.getValueAt(0,4).toString());
              conec.insert("insert into asignarcurso(idcatedra,idcatedratico,codfacultad,fecha) values("+tablaasignacion.getValueAt(0,2)+","+tablaasignacion.getValueAt(0,0)+","+codfac+",'"+fechaActual+"')");  
         //   JOptionPane.showMessageDialog(this,"insert into asignarcurso(idcatedra,idcatedratico,codfacultad,fecha) values("+tablaasignacion.getValueAt(0,2)+","+tablaasignacion.getValueAt(0,0)+","+codfac+","+fechaActual+")");
            ((DefaultTableModel) tablaasignacion.getModel()).removeRow(0);
            
            }
            //cerramos la conexion
            conec.closeConection();
           JOptionPane.showMessageDialog(this, "Agregado exitosamente");
           limpiar();
           }else{
                JOptionPane.showMessageDialog(this, "Se debe de seleccionar el un docente y un curso almenos para continuar");
           }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnasignarActionPerformed

    public void clear(){
     idcatedratico=-1;
     nombre="";
     catedra=-1;
     materia="";
    idmateria=-1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmasignaciondecatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmasignaciondecatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmasignaciondecatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmasignaciondecatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmasignaciondecatedra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCatedratico;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnasignar;
    private javax.swing.JButton btncatedra;
    private javax.swing.JComboBox<String> cbofacultad;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcatedras;
    private javax.swing.JLabel lblcatedraticos;
    private javax.swing.JTable tablaasignacion;
    // End of variables declaration//GEN-END:variables

    private int getcodigo(String facultad) {
        // retornamos su correspondiente codigo de facultad
        if(facultad.equalsIgnoreCase("Ingenieria en Sistemas")){
            return 1790;
        }else if(facultad.equalsIgnoreCase("Ciencias Juridicas y Sociales")){
            return 1750;
        }else if(facultad.equalsIgnoreCase("Administracion")){
            return 1722;
        }else if(facultad.equalsIgnoreCase("Psicologia Clinica")){
            return 3004;
        }else if(facultad.equalsIgnoreCase("Psicologia Industrial")){
            return 6301;
        }else if(facultad.equalsIgnoreCase("Ingles")){
              return 8026;
        }
    return -1;
    }

    private boolean isvalid() {
        if(tablaasignacion.getRowCount()>0)return true;
        return false;
    }

    private void limpiar() {
      
        while (tablaasignacion.getRowCount()>0) {
            ((DefaultTableModel) tablaasignacion.getModel()).removeRow(0);
            
            }
        idcatedratico=-1;
        nombre="";
        catedra=-1;
        materia="";
        idmateria=-1;
    }
}
