/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticaciondeproceso;

import automaticaciondeproceso.conections.Conection;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wwwca
 */
public class frmBuscarCatedra extends javax.swing.JFrame {
        public int idcatedra=-1;
        public int count=-1;
        public String nombre="";
        
    /**
     * Creates new form BuscarCatedra
     */
    public frmBuscarCatedra() {
        initComponents();
        this.setSize(new Dimension(420,270));
         this.getRootPane().setDefaultButton(btnbuscar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnombrecatedra = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecatedra = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Curso");
        setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("NombreCatedra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(21, 20, 90, 14);

        txtnombrecatedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecatedraActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombrecatedra);
        txtnombrecatedra.setBounds(130, 20, 134, 20);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(270, 20, 90, 23);

        tablecatedra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codcate", "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablecatedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecatedraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecatedra);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 340, 98);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(240, 160, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automaticaciondeproceso/fondo4.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -290, 410, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrecatedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecatedraActionPerformed
       
       
    }//GEN-LAST:event_txtnombrecatedraActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
 try{ 
            Conection conec=new Conection();
          // ResultSet rs= conec.select("select * from catedratico where primernombre like '%"+txtprimnombre.getText()+"%' and segundonombre like '%"+txtsegundonombre.getText()+"%' and primerapellido like '%"+txtprimapellido.getText()+"%' and segundoapellido like '%"+txtsegunapellido.getText()+"%'");
           ResultSet rs= conec.select("select * from catedra where nombre like '%"+txtnombrecatedra.getText()+"%'");
          while (tablecatedra.getRowCount() > 0) {
            ((DefaultTableModel) tablecatedra.getModel()).removeRow(0);
            
            }
            
            boolean issomething=false;
           if(rs!=null){
                  int columns = rs.getMetaData().getColumnCount();
                  
             while (rs.next())
               {
                   issomething=true;
                    Object[] row = new Object[columns];
                    for (int i = 1; i <= 2; i++)
                    {  
                         row[i - 1] = rs.getObject(i); // 1
                          //JOptionPane.showMessageDialog(this, "Agregado exitosamente " + rs.getObject(i).toString() );

                    }
                    
                        ((DefaultTableModel)tablecatedra.getModel()).insertRow(rs.getRow() - 1,row);
                }
             
            }
           if(!issomething){
                JOptionPane.showMessageDialog(this, "No se a encontrado ningun resultado que conincida "  );
           }
          
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      JOptionPane.showMessageDialog(this, "se ha selecionado exitosamente" );
      data.idmateria=idcatedra;
      data.materia=nombre;
       this.dispose();
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablecatedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecatedraMouseClicked
   count=tablecatedra.getSelectedRow();
   idcatedra=(int) tablecatedra.getValueAt(count, 0);        // TODO add your handling code here:
   nombre=(String) tablecatedra.getValueAt(count, 1);
    }//GEN-LAST:event_tablecatedraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuscarCatedra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablecatedra;
    private javax.swing.JTextField txtnombrecatedra;
    // End of variables declaration//GEN-END:variables
}
