/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticaciondeproceso;

import automaticaciondeproceso.conections.Conection;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author wwwca
 */
public class frmBuscarCatedratico extends javax.swing.JFrame {
public int idcatedratico=0;

public int count=-1;
public String nombre="";
    /**
     * Creates new form frmBuscarCatedratico
     */
    public frmBuscarCatedratico() {
        initComponents();
        this.setSize(new Dimension(1220,240));
        this.getRootPane().setDefaultButton(btnbuscar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablacatedratico = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtprimnombre = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtprimapellido = new javax.swing.JTextField();
        txtsegunnombre = new javax.swing.JTextField();
        txtsegundonombre = new javax.swing.JLabel();
        txtsegunapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Docente");
        getContentPane().setLayout(null);

        tablacatedratico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codcatedratico", "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablacatedratico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacatedraticoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacatedratico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 1160, 98);

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar);
        btnagregar.setBounds(1060, 150, 100, 23);

        jLabel1.setText("primer Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 14);

        txtprimnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprimnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtprimnombre);
        txtprimnombre.setBounds(120, 20, 150, 20);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(1110, 20, 80, 23);

        jLabel2.setText("primer Apellido");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 20, 110, 14);

        txtprimapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprimapellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtprimapellido);
        txtprimapellido.setBounds(610, 20, 200, 20);

        txtsegunnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsegunnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtsegunnombre);
        txtsegunnombre.setBounds(380, 20, 140, 20);

        txtsegundonombre.setText("segundo nombre");
        getContentPane().add(txtsegundonombre);
        txtsegundonombre.setBounds(280, 20, 110, 14);

        txtsegunapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsegunapellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtsegunapellido);
        txtsegunapellido.setBounds(920, 20, 180, 20);

        jLabel4.setText("Segundo Apellido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(820, 20, 150, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automaticaciondeproceso/fondo4.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -290, 1210, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprimnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprimnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprimnombreActionPerformed

    private void txtprimapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprimapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprimapellidoActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
       
        try{ 
            Conection conec=new Conection();
          // ResultSet rs= conec.select("select * from catedratico where primernombre like '%"+txtprimnombre.getText()+"%' and segundonombre like '%"+txtsegundonombre.getText()+"%' and primerapellido like '%"+txtprimapellido.getText()+"%' and segundoapellido like '%"+txtsegunapellido.getText()+"%'");
           ResultSet rs= conec.select("select * from catedratico where primernombre like '%"+txtprimnombre.getText()+"%' and segundonombre like '%"+txtsegunnombre.getText()+"%' and primerapellido like '%"+txtprimapellido.getText()+"%' and segundoapellido like '%"+txtsegunapellido.getText()+"%'");
          while (tablacatedratico.getRowCount() > 0) {
            ((DefaultTableModel) tablacatedratico.getModel()).removeRow(0);
            
            }
            
             boolean issomething=false;
           if(rs!=null){
                  int columns = rs.getMetaData().getColumnCount();
             while (rs.next())
               {  
                   issomething=true;
                    Object[] row = new Object[columns];
                    for (int i = 1; i <= 2; i++)
                    {  if(i==2){
                        row[i - 1] = rs.getObject(i)+" "+rs.getObject(i+1)+" "+rs.getObject(i+2)+" "+rs.getObject(i+3); // 
                    }else{
                         row[i - 1] = rs.getObject(i); // 
                    }
                          //JOptionPane.showMessageDialog(this, "Agregado exitosamente " + rs.getObject(i).toString() );

                    }
                    
                        ((DefaultTableModel) tablacatedratico.getModel()).insertRow(rs.getRow() - 1,row);
                }
             
               
            }
           
            if(!issomething){
                 JOptionPane.showMessageDialog(this, "No se encontro a un Doncente que conincida con la busqueda "  );
             }
            
          
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtsegunnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsegunnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsegunnombreActionPerformed

    private void txtsegunapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsegunapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsegunapellidoActionPerformed

    private void tablacatedraticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacatedraticoMouseClicked
        count=tablacatedratico.getSelectedRow();
        idcatedratico=(int) tablacatedratico.getValueAt(count, 0);
        nombre=(String) tablacatedratico.getValueAt(count, 1);
    }//GEN-LAST:event_tablacatedraticoMouseClicked

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
   JOptionPane.showMessageDialog(this, "Seleccionado exitosamente " );
      data.idcatedratico=idcatedratico;
      data.nombre=nombre;
   this.dispose();

    }//GEN-LAST:event_btnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuscarCatedratico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacatedratico;
    private javax.swing.JTextField txtprimapellido;
    private javax.swing.JTextField txtprimnombre;
    private javax.swing.JTextField txtsegunapellido;
    private javax.swing.JLabel txtsegundonombre;
    private javax.swing.JTextField txtsegunnombre;
    // End of variables declaration//GEN-END:variables
}
