/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticaciondeproceso;

import automaticaciondeproceso.conections.Conection;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.DocumentException;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wwwca
 */
public class frmImprimir extends javax.swing.JFrame {

    /**
     * Creates new form frmImprimir
     */
    public frmImprimir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        cbofacultad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar Lista");

        jLabel1.setText("facultad");

        btngenerar.setText("Generar");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        cbofacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en Sistemas", "Ciencias Juridicas y Sociales", "Administracion", "Psicologia Clinica", "Psicologia Industrial", "Ingles" }));
        cbofacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbofacultadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbofacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(cbofacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngenerar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
        // la direccion donde se almacenara
       Date s=new Date();
       
       System.out.println(""+s);
        
     //String fecha=""+ Integer.toString(c1.get(Calendar.DATE))+"/"+Integer.toString(c1.get(Calendar.MONTH)+1)+"/"+Integer.toString(c1.get(Calendar.YEAR));
        
        JFileChooser chDialog=new JFileChooser();
        int op=chDialog.showSaveDialog(this);
         File fw;
        if(op==JFileChooser.APPROVE_OPTION){
                fw=chDialog.getSelectedFile();


            //File fw=new File("C:/Users/wwwca/Documents/NetBeansProjects/automaticaciondeproceso/myreporte.pdf");
              Generarpdf gpdf=new Generarpdf(); // creamos un instancia de GenerarPdf en el cual tenemos los datos para poder programarlo

             try{ 
                  Conection conec=new Conection();
                  // realizamo una conexion con la base de datos



                int codfac=takecodfacultad(cbofacultad.getSelectedItem().toString()); 
                 System.out.println(codfac);
                // ResultSet rs= conec.select("select * from catedratico where primernombre like '%"+txtprimnombre.getText()+"%' and segundonombre like '%"+txtsegundonombre.getText()+"%' and primerapellido like '%"+txtprimapellido.getText()+"%' and segundoapellido like '%"+txtsegunapellido.getText()+"%'");
                int mesini=-1;
                int mesfin=-1;
                 Calendar c1=Calendar.getInstance();
                 
                 
                   if(c1.get(Calendar.MONTH)+1<7){
                       mesini=0;
                       mesfin=7;
                   }else{
                        mesini=7;
                        mesfin=12;
                   }
                   String fecha1=Integer.toString(c1.get(Calendar.YEAR))+"-"+mesini+"-"+0;
                   String fecha2=Integer.toString(c1.get(Calendar.YEAR))+"-"+mesfin+"-"+0;
                   System.out.println(fecha1.toString());
        
                ResultSet rs= conec.select("select asig.idcatedratico,doc.primernombre,doc.segundonombre,doc.primerapellido,doc.segundoapellido,cat.nombre from asignarcurso asig left join catedra cat on asig.idcatedra=cat.idcatedra inner join catedratico doc on asig.idcatedratico=doc.idcatedratico  where asig.codfacultad="+codfac+" and asig.fecha between '"+fecha1+"' and '"+fecha2+"' order by asig.idcatedratico");
                   System.out.println("select asig.idcatedratico,doc.primernombre,doc.segundonombre,doc.primerapellido,doc.segundoapellido,cat.nombre from asignarcurso asig left join catedra cat on asig.idcatedra=cat.idcatedra inner join catedratico doc on asig.idcatedratico=doc.idcatedratico  where asig.codfacultad="+codfac+" and asig.fecha between '"+fecha1+"' and '"+fecha2+"' order by asig.idcatedratico");


                 if(rs!=null){
                       gpdf.createPdfs(fw.getPath()+".pdf",cbofacultad.getSelectedItem().toString(),rs);
                        JOptionPane.showMessageDialog(this, "Formularios Generados Exitosamente"  );
                 }else{
                      JOptionPane.showMessageDialog(this, "No hay registros para buscar en esta facultad"  );
                 }

              } catch (SQLException ex) {
                  Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IOException ex) {
                  Logger.getLogger(frmImprimir.class.getName()).log(Level.SEVERE, null, ex);
              } catch (DocumentException ex) {
                  Logger.getLogger(frmImprimir.class.getName()).log(Level.SEVERE, null, ex);
              }

            
            
            
        }        
           // JOptionPane.showMessageDialog(rootPane, cbofacultad.getSelectedItem());
           
           
       // gpdf.createPDF(fw);
    }//GEN-LAST:event_btngenerarActionPerformed

    private void cbofacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbofacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbofacultadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmImprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerar;
    private javax.swing.JComboBox<String> cbofacultad;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private int takecodfacultad(String nfacultad) {
        if(nfacultad.equalsIgnoreCase("Ingenieria en Sistemas")){
            return 1790;
        }else if(nfacultad.equalsIgnoreCase("Ciencias Juridicas y Sociales")){
            return 1750;
        }else if(nfacultad.equalsIgnoreCase("Administracion")){
            return 1722;
        }else if(nfacultad.equalsIgnoreCase("Psicologia Clinica")){
            return 3004;
        }else if(nfacultad.equalsIgnoreCase("Psicologia Industrial")){
            return 6301;
        }else if(nfacultad.equalsIgnoreCase("Ingles")){
              return 8026;
        }
    return -1;
    }
}
