/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticaciondeproceso;

import automaticaciondeproceso.conections.Conection;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwca
 */
public class frmregistrocatedraticos extends javax.swing.JFrame {
    

    /**
     * Creates new form frmregistrocatedraticos
     */
    public frmregistrocatedraticos() {
        initComponents();
         this.setSize(new Dimension(420,340));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtprimernombre = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtsegundonombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprimerapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsegundoapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Catedratico");
        getContentPane().setLayout(null);

        jLabel2.setText("Primer Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 66, 90, 14);
        getContentPane().add(txtprimernombre);
        txtprimernombre.setBounds(170, 60, 143, 30);

        btnregistrar.setText("registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar);
        btnregistrar.setBounds(43, 254, 110, 33);

        jLabel3.setText("segundo Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 99, 100, 14);
        getContentPane().add(txtsegundonombre);
        txtsegundonombre.setBounds(170, 100, 143, 32);

        jLabel4.setText("Primer Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 146, 100, 14);
        getContentPane().add(txtprimerapellido);
        txtprimerapellido.setBounds(170, 140, 143, 33);

        jLabel5.setText("segundo Apellido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(43, 191, 110, 14);
        getContentPane().add(txtsegundoapellido);
        txtsegundoapellido.setBounds(170, 180, 143, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automaticaciondeproceso/fondo4.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 420, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
       
           try {
           if(isvalid()){   
            Conection conec=new Conection();
            conec.insert("insert into catedratico(primernombre,segundonombre,primerapellido,segundoapellido) values('"+txtprimernombre.getText()+"','"+txtsegundonombre.getText()+"','"+txtprimerapellido.getText()+"','"+txtsegundoapellido.getText()+"')");
            JOptionPane.showMessageDialog(this, "Agregado exitosamente");
            limpiar();
           }else{
            JOptionPane.showMessageDialog(this, "Para Poder Registrar Un Docente tiene que llenar todos los campos");
           }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregistrocatedraticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregistrocatedraticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregistrocatedraticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregistrocatedraticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmregistrocatedraticos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrup;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtprimerapellido;
    private javax.swing.JTextField txtprimernombre;
    private javax.swing.JTextField txtsegundoapellido;
    private javax.swing.JTextField txtsegundonombre;
    // End of variables declaration//GEN-END:variables

    private boolean isvalid() {
        if(txtsegundonombre.getText().length()==0){
            return false;
        }else if(txtsegundonombre.getText().length()==0){
            return false;
        }else if(txtprimerapellido.getText().length()==0){
            return false;
        }else if(txtsegundoapellido.getText().length()==0){
            return false;
        }
        return true;
    }

    private void limpiar() {
            txtprimerapellido.setText("");
            txtprimernombre.setText("");
            txtsegundoapellido.setText("");
            txtsegundonombre.setText("");
    }
}
