/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticaciondeproceso;

import automaticaciondeproceso.conections.Conection;
import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwca
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setSize(new Dimension(1350, 650));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnregistrarcurso = new javax.swing.JButton();
        btnregistrardocente = new javax.swing.JButton();
        btnasignarcurso = new javax.swing.JButton();
        btnpasword = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnregistrarcurso.setText("Registrar Curso");
        btnregistrarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarcursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrarcurso);
        btnregistrarcurso.setBounds(310, 530, 123, 64);

        btnregistrardocente.setText("Registrar Docente");
        btnregistrardocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrardocenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrardocente);
        btnregistrardocente.setBounds(450, 530, 119, 64);

        btnasignarcurso.setText("Asignar Cursos");
        btnasignarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignarcursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnasignarcurso);
        btnasignarcurso.setBounds(570, 530, 139, 66);

        btnpasword.setText("Cambiar contraseña");
        btnpasword.setEnabled(false);
        btnpasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnpasword);
        btnpasword.setBounds(860, 530, 141, 64);

        jButton5.setText("Imprimir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 530, 127, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automaticaciondeproceso/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnasignarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignarcursoActionPerformed
        // TODO add your handling code here:
       frmasignaciondecatedra asing= new frmasignaciondecatedra();
       asing.setAlwaysOnTop(true);
       asing.setVisible(true);
    }//GEN-LAST:event_btnasignarcursoActionPerformed

    private void btnregistrardocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrardocenteActionPerformed
        frmregistrocatedraticos catedratico=new frmregistrocatedraticos();
       catedratico.setAlwaysOnTop(true);
        catedratico.setVisible(true);     
    }//GEN-LAST:event_btnregistrardocenteActionPerformed

    private void btnregistrarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarcursoActionPerformed
            frmregistrarcatedra cat=new frmregistrarcatedra();
            cat.setAlwaysOnTop(true);
            cat.setVisible(true);
    }//GEN-LAST:event_btnregistrarcursoActionPerformed

    private void btnpaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaswordActionPerformed
            frmCambiarConstrasenya chagcon=new frmCambiarConstrasenya();
            chagcon.pack();
            chagcon.setAlwaysOnTop(true);
            chagcon.setVisible(true);
    }//GEN-LAST:event_btnpaswordActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                // JOptionPane.showMessageDialog(this, " " + this.getClass().getCanonicalName() );
          System.out.println (new File ("esto.pdf").getAbsolutePath ());
  
            frmImprimir impri=new frmImprimir();         
            impri.setAlwaysOnTop(true);
            impri.setVisible(true);
       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnasignarcurso;
    private javax.swing.JButton btnpasword;
    private javax.swing.JButton btnregistrarcurso;
    private javax.swing.JButton btnregistrardocente;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
